export type AppLanguage = "en" | "bn";

export const appCopy = {
  en: {
    common: {
      language: "Language",
      english: "English",
      bangla: "Bangla",
      teacher: "Teacher",
      institution: "Institution",
      close: "Close",
      back: "Back",
      loading: "Loading...",
      dashboard: "Dashboard",
      settings: "Settings",
      logout: "Logout",
      active: "Active",
      workspace: "Workspace",
    },
    auth: {
      accountAccess: "Account access",
      secureSignIn: "Secure sign in",
      institutionAccess: "Institution access",
      teacherAccess: "Teacher access",
      fullName: "Full name",
      email: "Email address",
      password: "Password",
      forgotPassword: "Forgot password?",
      signIn: "Sign in",
      createAccount: "Create account",
      pleaseWait: "Please wait...",
      noAccount: "No account yet?",
      registerFree: "Register free",
      alreadyAccount: "Already have an account?",
      acceptTerms: "I agree to the Terms and Conditions.",
      termsTitle: "Terms and Conditions",
      termsHint: "Please review before creating your account.",
      openFullPage: "Open full page",
      mustAcceptTerms: "You must accept the terms and conditions to continue.",
      welcomeBack: "Welcome Back",
      signInSubtitle: "Sign in to your account to continue",
      registerTeacherTitle: "Register as Teacher",
      registerTeacherSubtitle: "Create your account to start offering your expertise",
      registerInstitutionTitle: "Register as Institution",
      registerInstitutionSubtitle: "Create your account to start hiring qualified teachers",
      createAccountTitle: "Create your account",
      createAccountSubtitle: "Choose your workspace and continue.",
      teacherAccount: "Teacher account",
      teacherAccountDescription: "Create your profile, manage requests, and connect with institutions.",
      institutionAccount: "Institution account",
      institutionAccountDescription: "Set up your hiring workspace, post jobs, and manage teacher outreach.",
      startAsTeacher: "Start as Teacher",
      startAsInstitution: "Start as Institution",
    },
    nav: {
      dashboard: "Dashboard",
      editProfile: "Edit Profile",
      createProfile: "Create Profile",
      browseJobs: "Browse Jobs",
      manageJobPosts: "Manage Job Posts",
      messages: "Messages",
      changePassword: "Change Password",
      receivedRequests: "Received Requests",
      sentRequests: "Sent Requests",
      browseTeachers: "Browse Teachers",
      hiredTeachers: "Hired Teachers",
    },
    dashboard: {
      teacherWorkspace: "Teacher workspace",
      institutionWorkspace: "Institution workspace",
      jobsMessagesHiring: "Jobs, messages, and hiring activity",
      postsMessagesHiring: "Posts, messages, and hiring activity",
    },
    terms: {
      title: "Terms and Conditions",
      intro:
        "These terms govern the use of Al Asatizah as a platform for institutions and teachers to connect, create profiles, communicate, and manage hiring activity.",
      accountTitle: "1. Account responsibility",
      accountBody:
        "Users must provide accurate registration information and are responsible for activity performed through their account.",
      contentTitle: "2. Profile and content accuracy",
      contentBody:
        "Teachers and institutions should keep profile information, job details, messages, and requests truthful, relevant, and up to date.",
      useTitle: "3. Respectful use",
      useBody:
        "Users must not misuse the platform, send harmful or misleading content, impersonate others, or use the service for unlawful activity.",
      hiringTitle: "4. Hiring and communication",
      hiringBody:
        "Al Asatizah facilitates connection and communication, but hiring decisions, verification, and agreements remain the responsibility of the teacher and institution involved.",
      rightsTitle: "5. Platform rights",
      rightsBody:
        "We may update platform features, moderate inappropriate content, and suspend accounts that violate these terms or harm the platform community.",
      acceptanceTitle: "6. Acceptance",
      acceptanceBody: "By registering, you confirm that you have read and accepted these terms and conditions.",
      backToRegister: "Back to registration",
    },
  },
  bn: {
    common: {
      language: "ভাষা",
      english: "English",
      bangla: "বাংলা",
      teacher: "শিক্ষক",
      institution: "প্রতিষ্ঠান",
      close: "বন্ধ করুন",
      back: "ফিরে যান",
      loading: "লোড হচ্ছে...",
      dashboard: "ড্যাশবোর্ড",
      settings: "সেটিংস",
      logout: "লগআউট",
      active: "সক্রিয়",
      workspace: "ওয়ার্কস্পেস",
    },
    auth: {
      accountAccess: "অ্যাকাউন্ট প্রবেশ",
      secureSignIn: "নিরাপদ সাইন ইন",
      institutionAccess: "প্রতিষ্ঠান প্রবেশ",
      teacherAccess: "শিক্ষক প্রবেশ",
      fullName: "পূর্ণ নাম",
      email: "ইমেইল ঠিকানা",
      password: "পাসওয়ার্ড",
      forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
      signIn: "সাইন ইন",
      createAccount: "অ্যাকাউন্ট তৈরি করুন",
      pleaseWait: "অপেক্ষা করুন...",
      noAccount: "এখনও অ্যাকাউন্ট নেই?",
      registerFree: "ফ্রি নিবন্ধন",
      alreadyAccount: "আগে থেকেই অ্যাকাউন্ট আছে?",
      acceptTerms: "আমি শর্তাবলী মেনে নিচ্ছি।",
      termsTitle: "শর্তাবলী",
      termsHint: "অ্যাকাউন্ট তৈরির আগে অনুগ্রহ করে পড়ে নিন।",
      openFullPage: "পূর্ণ পৃষ্ঠা খুলুন",
      mustAcceptTerms: "এগোতে হলে আপনাকে শর্তাবলী মেনে নিতে হবে।",
      welcomeBack: "ফিরে আসায় স্বাগতম",
      signInSubtitle: "চালিয়ে যেতে আপনার অ্যাকাউন্টে সাইন ইন করুন",
      registerTeacherTitle: "শিক্ষক হিসেবে নিবন্ধন",
      registerTeacherSubtitle: "আপনার দক্ষতা উপস্থাপনের জন্য অ্যাকাউন্ট তৈরি করুন",
      registerInstitutionTitle: "প্রতিষ্ঠান হিসেবে নিবন্ধন",
      registerInstitutionSubtitle: "যোগ্য শিক্ষক নিয়োগ শুরু করতে অ্যাকাউন্ট তৈরি করুন",
      createAccountTitle: "আপনার অ্যাকাউন্ট তৈরি করুন",
      createAccountSubtitle: "আপনার ওয়ার্কস্পেস নির্বাচন করে এগিয়ে যান।",
      teacherAccount: "শিক্ষক অ্যাকাউন্ট",
      teacherAccountDescription: "প্রোফাইল তৈরি করুন, রিকোয়েস্ট ম্যানেজ করুন এবং প্রতিষ্ঠানের সাথে যুক্ত হন।",
      institutionAccount: "প্রতিষ্ঠান অ্যাকাউন্ট",
      institutionAccountDescription: "হায়ারিং ওয়ার্কস্পেস তৈরি করুন, চাকরি পোস্ট করুন এবং শিক্ষক যোগাযোগ ম্যানেজ করুন।",
      startAsTeacher: "শিক্ষক হিসেবে শুরু করুন",
      startAsInstitution: "প্রতিষ্ঠান হিসেবে শুরু করুন",
    },
    nav: {
      dashboard: "ড্যাশবোর্ড",
      editProfile: "প্রোফাইল সম্পাদনা",
      createProfile: "প্রোফাইল তৈরি",
      browseJobs: "চাকরি দেখুন",
      manageJobPosts: "জব পোস্ট ম্যানেজ করুন",
      messages: "মেসেজ",
      changePassword: "পাসওয়ার্ড পরিবর্তন",
      receivedRequests: "প্রাপ্ত রিকোয়েস্ট",
      sentRequests: "পাঠানো রিকোয়েস্ট",
      browseTeachers: "শিক্ষক খুঁজুন",
      hiredTeachers: "নিয়োগকৃত শিক্ষক",
    },
    dashboard: {
      teacherWorkspace: "শিক্ষক ওয়ার্কস্পেস",
      institutionWorkspace: "প্রতিষ্ঠান ওয়ার্কস্পেস",
      jobsMessagesHiring: "চাকরি, মেসেজ এবং হায়ারিং কার্যক্রম",
      postsMessagesHiring: "পোস্ট, মেসেজ এবং হায়ারিং কার্যক্রম",
    },
    terms: {
      title: "শর্তাবলী",
      intro:
        "শিক্ষক ও প্রতিষ্ঠানকে সংযুক্ত করা, প্রোফাইল তৈরি, যোগাযোগ এবং নিয়োগ কার্যক্রম পরিচালনার জন্য Al Asatizah প্ল্যাটফর্ম ব্যবহারে এই শর্তাবলী প্রযোজ্য।",
      accountTitle: "১. অ্যাকাউন্টের দায়িত্ব",
      accountBody: "ব্যবহারকারীকে সঠিক তথ্য দিয়ে নিবন্ধন করতে হবে এবং নিজের অ্যাকাউন্টের কার্যক্রমের দায়িত্ব নিজেকেই নিতে হবে।",
      contentTitle: "২. প্রোফাইল ও তথ্যের সঠিকতা",
      contentBody: "শিক্ষক ও প্রতিষ্ঠানকে প্রোফাইল, চাকরির তথ্য, মেসেজ এবং রিকোয়েস্ট সত্য, প্রাসঙ্গিক ও হালনাগাদ রাখতে হবে।",
      useTitle: "৩. সম্মানজনক ব্যবহার",
      useBody: "কেউ প্ল্যাটফর্ম অপব্যবহার করতে পারবে না, ক্ষতিকর বা বিভ্রান্তিকর তথ্য পাঠাতে পারবে না, অন্যের পরিচয় ব্যবহার করতে পারবে না।",
      hiringTitle: "৪. নিয়োগ ও যোগাযোগ",
      hiringBody:
        "Al Asatizah যোগাযোগ ও সংযোগের সুযোগ দেয়, তবে চূড়ান্ত নিয়োগ সিদ্ধান্ত, যাচাই এবং চুক্তির দায়িত্ব সংশ্লিষ্ট শিক্ষক ও প্রতিষ্ঠানের।",
      rightsTitle: "৫. প্ল্যাটফর্মের অধিকার",
      rightsBody: "আমরা ফিচার আপডেট, অনুপযুক্ত কনটেন্ট নিয়ন্ত্রণ এবং নীতিভঙ্গকারী অ্যাকাউন্ট সীমিত বা স্থগিত করতে পারি।",
      acceptanceTitle: "৬. সম্মতি",
      acceptanceBody: "নিবন্ধনের মাধ্যমে আপনি নিশ্চিত করছেন যে আপনি এই শর্তাবলী পড়েছেন এবং মেনে নিয়েছেন।",
      backToRegister: "নিবন্ধনে ফিরে যান",
    },
  },
} as const;

export type AppCopy = (typeof appCopy)[AppLanguage];
