export const redesignImages = {
  heroMain: "/Hero.png",
  flexibilityMain: "/redesign/cta-flexibility-main.png",
  opportunitySchool: "/redesign/opportunity-school-teacher.png",
  opportunityOnline: "/redesign/opportunity-online-tutor.png",
  opportunitySpecialist: "/redesign/opportunity-subject-specialist.png",
  opportunityParttime: "/redesign/opportunity-part-time-teacher.png",
  stepOne: "/redesign/process-create-profile.png",
  stepTwo: "/redesign/process-discover-match.png",
  stepThree: "/redesign/process-chat-confirm.png",
  benefitOne: "/redesign/benefit-profile-dashboard.png",
  benefitTwo: "/redesign/benefit-institution-review.png",
  benefitThree: "/redesign/benefit-direct-messaging.png",
  benefitFour: "/redesign/benefit-hiring-confirmation.png",
  teacherCard: "/redesign/audience-teacher-profile.png",
  institutionCard: "/redesign/audience-institution-profile.png",
  testimonialOne: "/redesign/testimonial-admin-representative.png",
  testimonialTwo: "/redesign/testimonial-professional-teacher.png",
  testimonialThree: "/redesign/testimonial-education-coordinator.png",
  faqCover: "/redesign/faq-cover.png",
  logoMark: "/redesign/logo-mark.png",
} as const;
