export const redesignImages = {
  heroMain: "/landing-hero-main-v2.png",
  flexibilityMain: "/landing-cta-flexibility-main-v2.png",
  opportunitySchool: "/landing-opportunity-school-teacher-v2.png",
  opportunityOnline: "/landing-opportunity-online-tutor-v2.png",
  opportunitySpecialist: "/landing-opportunity-subject-specialist-v2.png",
  opportunityParttime: "/landing-opportunity-part-time-teacher-v2.png",
  stepOne: "/landing-process-create-profile-v2.png",
  stepTwo: "/landing-process-discover-match-v2.png",
  stepThree: "/landing-process-chat-confirm-v2.png",
  benefitOne: "/landing-benefit-profile-dashboard-v2.png",
  benefitTwo: "/landing-benefit-institution-review-v2.png",
  benefitThree: "/landing-benefit-direct-messaging-v2.png",
  benefitFour: "/landing-benefit-hiring-confirmation-v2.png",
  teacherCard: "/landing-audience-teacher-profile-v2.png",
  institutionCard: "/landing-audience-institution-profile-v2.png",
  testimonialOne: "/landing-testimonial-admin-representative-v2.png",
  testimonialTwo: "/landing-testimonial-professional-teacher-v2.png",
  testimonialThree: "/landing-testimonial-education-coordinator-v2.png",
  faqCover: "/landing-faq-cover-v2.png",
  logoMark: "/landing-logo-mark-v2.png",
} as const;
