export const redesignImages = {
  heroMain: "/landing-hero-main.png",
  flexibilityMain: "/landing-cta-flexibility-main.png",
  opportunitySchool: "/landing-opportunity-school-teacher.png",
  opportunityOnline: "/landing-opportunity-online-tutor.png",
  opportunitySpecialist: "/landing-opportunity-subject-specialist.png",
  opportunityParttime: "/landing-opportunity-part-time-teacher.png",
  stepOne: "/landing-process-create-profile.png",
  stepTwo: "/landing-process-discover-match.png",
  stepThree: "/landing-process-chat-confirm.png",
  benefitOne: "/landing-benefit-profile-dashboard.png",
  benefitTwo: "/landing-benefit-institution-review.png",
  benefitThree: "/landing-benefit-direct-messaging.png",
  benefitFour: "/landing-benefit-hiring-confirmation.png",
  teacherCard: "/landing-audience-teacher-profile.png",
  institutionCard: "/landing-audience-institution-profile.png",
  testimonialOne: "/landing-testimonial-admin-representative.png",
  testimonialTwo: "/landing-testimonial-professional-teacher.png",
  testimonialThree: "/landing-testimonial-education-coordinator.png",
  faqCover: "/landing-faq-cover.png",
  logoMark: "/landing-logo-mark.png",
} as const;
